 #### roles internas da FFLCH ####
- name: fflch.tasks
  src: https://github.com/fflch/ansible-role-tasks.git
  version: 1.0.22

- name: fflch.proaluno
  src: https://github.com/fflch/ansible-role-proaluno.git
  version: 1.0.5

- name: fflch.domain-member
  src: https://github.com/fflch/ansible-role-domain-member.git
  version: 1.0.5


#### roles da comunidade ####

- src: hispanico.nginx_revproxy
  version: v1.7.0

- src: geerlingguy.ntp
  version: 2.3.1

- src: geerlingguy.pip
  version: 2.2.0

- src: cmprescott.chrome
  version: 0.2.4

- src: Stouts.hostname
- src: adriagalin.timezone
- src: infOpen.locales
- src: ontic.ntp
- src: blackstar257.resolv


